/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransmissionBboxRouteImport } from './routes/api.transmission-bbox'
import { Route as ApiPipelinesBboxRouteImport } from './routes/api.pipelines-bbox'
import { Route as ApiPipelinesAllRouteImport } from './routes/api.pipelines-all'
import { Route as ApiOptimalPlacesRouteImport } from './routes/api.optimal-places'
import { Route as ApiAnalyzeRouteImport } from './routes/api.analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransmissionBboxRoute = ApiTransmissionBboxRouteImport.update({
  id: '/api/transmission-bbox',
  path: '/api/transmission-bbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelinesBboxRoute = ApiPipelinesBboxRouteImport.update({
  id: '/api/pipelines-bbox',
  path: '/api/pipelines-bbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipelinesAllRoute = ApiPipelinesAllRouteImport.update({
  id: '/api/pipelines-all',
  path: '/api/pipelines-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOptimalPlacesRoute = ApiOptimalPlacesRouteImport.update({
  id: '/api/optimal-places',
  path: '/api/optimal-places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/optimal-places': typeof ApiOptimalPlacesRoute
  '/api/pipelines-all': typeof ApiPipelinesAllRoute
  '/api/pipelines-bbox': typeof ApiPipelinesBboxRoute
  '/api/transmission-bbox': typeof ApiTransmissionBboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/optimal-places': typeof ApiOptimalPlacesRoute
  '/api/pipelines-all': typeof ApiPipelinesAllRoute
  '/api/pipelines-bbox': typeof ApiPipelinesBboxRoute
  '/api/transmission-bbox': typeof ApiTransmissionBboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/optimal-places': typeof ApiOptimalPlacesRoute
  '/api/pipelines-all': typeof ApiPipelinesAllRoute
  '/api/pipelines-bbox': typeof ApiPipelinesBboxRoute
  '/api/transmission-bbox': typeof ApiTransmissionBboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/analyze'
    | '/api/optimal-places'
    | '/api/pipelines-all'
    | '/api/pipelines-bbox'
    | '/api/transmission-bbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/analyze'
    | '/api/optimal-places'
    | '/api/pipelines-all'
    | '/api/pipelines-bbox'
    | '/api/transmission-bbox'
  id:
    | '__root__'
    | '/'
    | '/api/analyze'
    | '/api/optimal-places'
    | '/api/pipelines-all'
    | '/api/pipelines-bbox'
    | '/api/transmission-bbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiOptimalPlacesRoute: typeof ApiOptimalPlacesRoute
  ApiPipelinesAllRoute: typeof ApiPipelinesAllRoute
  ApiPipelinesBboxRoute: typeof ApiPipelinesBboxRoute
  ApiTransmissionBboxRoute: typeof ApiTransmissionBboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transmission-bbox': {
      id: '/api/transmission-bbox'
      path: '/api/transmission-bbox'
      fullPath: '/api/transmission-bbox'
      preLoaderRoute: typeof ApiTransmissionBboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipelines-bbox': {
      id: '/api/pipelines-bbox'
      path: '/api/pipelines-bbox'
      fullPath: '/api/pipelines-bbox'
      preLoaderRoute: typeof ApiPipelinesBboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipelines-all': {
      id: '/api/pipelines-all'
      path: '/api/pipelines-all'
      fullPath: '/api/pipelines-all'
      preLoaderRoute: typeof ApiPipelinesAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/optimal-places': {
      id: '/api/optimal-places'
      path: '/api/optimal-places'
      fullPath: '/api/optimal-places'
      preLoaderRoute: typeof ApiOptimalPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiOptimalPlacesRoute: ApiOptimalPlacesRoute,
  ApiPipelinesAllRoute: ApiPipelinesAllRoute,
  ApiPipelinesBboxRoute: ApiPipelinesBboxRoute,
  ApiTransmissionBboxRoute: ApiTransmissionBboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
